### ISSUE TITLE
Onebeyond NPM ORG Access

### ISSUE THREAD

**Issue by UlisesGascon** [onebeyond/admin#39]
@inigomarquinez can you add [guidesmiths_bot](https://www.npmjs.com/~guidesmiths_bot) and [ulisesgascon](https://www.npmjs.com/~ulisesgascon) as owners of the new NPM org? [Doc related here](https://docs.npmjs.com/adding-members-to-your-organization)

**Comment by inigomarquinez** [comment]
@UlisesGascon , I've already set your user as owner and I've sent an invitation to [guidesmiths_bot](https://www.npmjs.com/~guidesmiths_bot) to joint the organization. Can you accept the invitation for the bot?

**Comment by UlisesGascon** [comment]
Yeah! It is working now :)
